version: '3.8'

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    privileged: true
    user: root
    ports:
      - 9696:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      #      - /Users/sushantkumar/Desktop/blog/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    networks:
      monitoring:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      monitoring:


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      monitoring:

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      monitoring:

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - 9100:9100

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: myapp
    ports:
      - "8081:8081"
    networks:
      - jenkins_net
    depends_on:
      - jenkins


networks:
    jenkins_net:
    default:
      name: prometheus-grafana
      driver: bridge


volumes:
  prometheus_data:
  grafana_data:
  influxdb_data:
  jenkins_home:
