global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: spring-boot-app
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: jenkins
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']