name: filebeat

#filebeat.inputs:
#  - type: log
#    enabled: true
#    paths:
#      - "/var/lib/docker/containers/*/*.log"

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - "/var/lib/docker/containers/${data.container.id}/*.log"

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_fields:
      target: ''
      fields:
        service: 'docker-logs'

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644