name: filebeat

filebeat.inputs:
  # Для сбора логов из папки logs вашего приложения
  - type: log
    enabled: true
    paths:
      - "/app_logs/**/*.log"
    fields:
      log_type: "app-file-logs"
      app_name: "spring-boot-app"
    fields_under_root: true
    scan_frequency: 30s  # ↑ Увеличить интервал сканирования
    close_inactive: 5m   # ↑ Увеличить время неактивности
    ignore_older: 24h    # ↑ Игнорировать старые файлы



processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_fields:
      target: ''
      fields:
        service: 'filebeat'

output.logstash:
  hosts: ["logstash:5044"]
  bulk_max_size: 20
  timeout: 30s

logging.level: warning
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644